site_name: Backup Secretary
site_url: https://entofmd.io
site_description: a discord bot made with NodeJS
site_author: EntOfMD

repo_url: https://github.com/EntOfMD/backup_secretary
edit_uri: ""

nav:
  - Home: index.md
  - Installation: installation.md
  - About: about.md

theme:
  name: null
  hljs_languages:
    - yaml
    - js
    - go
  nav_style: dark
  custom_dir: "windmill_custom_theme/"

extra:
  version: 0.6
